version: "3"

services:
  influxdb:
    # :2.1.1
    image: influxdb:2.1.1
    container_name: influxdbvolumed

    # environment:
    #   INFLUXDB_ADMIN_USER: admin
    #   INFLUXDB_ADMIN_PASSWORD: Pass1234
    #   DOCKER_INFLUXDB_INIT_MODE: setup
    #   DOCKER_INFLUXDB_INIT_USERNAME: admin
    #   DOCKER_INFLUXDB_INIT_PASSWORD: Pass1234
    #   DOCKER_INFLUXDB_INIT_ORG: test-org
    #   DOCKER_INFLUXDB_INIT_BUCKET: test-bucket
    #   DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: test-token
    env_file:
      - .env
    # entrypoint: ["./entrypoint.sh"]
    # restart: on-failure:10
    volumes:
      - influxdb2-storage:/var/lib/influxdb2
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.19
    container_name: telegrafvolumed
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf
    ports:
      - 8125:8125/udp
    env_file:
      - .env
    depends_on:
      - influxdb


  grafana:
  # -oss:8.4.3
    image: grafana/grafana
    container_name: grafanavolumed
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000


volumes:
  grafana-storage:
  influxdb2-storage: