version: "3"

services:
  influxdb:
    # :2.1.1
    image: influxdb:2.1.1
    container_name: influxdbvolumed
    env_file:
      - .env
    volumes:
      - influxdb2-storage:/var/lib/influxdb2
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.19
    container_name: telegrafvolumed
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf
    ports:
      - 8125:8125/udp
    env_file:
      - .env
    depends_on:
      - influxdb


  grafana:
  # -oss:8.4.3
    image: grafana/grafana
    container_name: grafanavolumed
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000


volumes:
  grafana-storage:
  influxdb2-storage: