version: '3'

networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

services:
  rmq0:
    image: rabbitmq:3.8-management-alpine
    hostname: rmq0
    networks:
      rabbitnet:
        aliases:
          - rmq0.local
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_NODENAME: "rmq0"
      RABBITMQ_CLUSTER_NODE_TYPE: "disc"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq cluster_formation.peer_discovery_backend rabbit_peer_discovery_classic_config"
    volumes:
      - ./data/rmq0:/var/lib/rabbitmq/mnesia
      - ./log/rmq0:/var/log/rabbitmq

  rmq1:
    image: rabbitmq:3.8-management-alpine
    hostname: rmq1
    networks:
      rabbitnet:
        aliases:
          - rmq1.local
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_NODENAME: "rmq0"
      RABBITMQ_CLUSTER_NODE_TYPE: "disc"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq cluster_formation.peer_discovery_backend rabbit_peer_discovery_classic_config"
    volumes:
      - ./data/rmq1:/var/lib/rabbitmq/mnesia
      - ./log/rmq1:/var/log/rabbitmq
  rmq2:
    image: rabbitmq:3.8-management-alpine
    hostname: rmq2
    networks:
      rabbitnet:
        aliases:
          - rmq2.local
    environment:
      RABBITMQ_ERLANG_COOKIE: "mycookie"
      RABBITMQ_NODENAME: "rmq0"
      RABBITMQ_CLUSTER_NODE_TYPE: "disc"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq cluster_formation.peer_discovery_backend rabbit_peer_discovery_classic_config"
    volumes:
      - ./data/rmq2:/var/lib/rabbitmq/mnesia
      - ./log/rmq2:/var/log/rabbitmq
  # perf-test:
  #   image: pivotalrabbitmq/perf-test:latest
  #   networks:
  #     - rabbitnet
  #   command:
  #     - --uri=amqp://haproxy.local
  #     - --servers-startup-timeout=45
  #     - --rate=100
  #     - --producers=10
  #     - --consumers=10
  #     - --confirm=32
  #     - --confirm-timeout=800
  #     - --flag=mandatory
  #     - --flag=persistent
  #     - --queue-args=x-queue-type=quorum
  #     - --auto-delete=false
  #     - --queue-pattern='perf-test-%03d'
  #     - --queue-pattern-from=0
  #     - --queue-pattern-to=9
  #   depends_on:
  #     - rmq0
  #     - rmq1
  #     - rmq2
  #     - haproxy
  #   restart: on-failure
  haproxy:
    image: haproxy:latest
    networks:
      rabbitnet:
        aliases:
          - haproxy.local
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq0
      - rmq1
      - rmq2
    ports:
      # HOST:CONTAINER
      - 15672:15672
      - 5672:5672