version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:nightly
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3004:3000"
      - "2224:22"



# "su - git" ile git user ına geçip
# "gitea admin user create --username admin -password Pass1234 --email 'ture.umut@gmail.com' --admin true --access-token true" ile user oluşturdum
