version: '3'
services:
  mssql:
    container_name: mssqlvolumed2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass1234
    volumes:
    - sql-data:/var/opt/mssql

volumes:
  sql-data:


# macos de 
# docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=Pass1234' -p 1433:1433 --name sqledge -d mcr.microsoft.com/azure-sql-edge

# windows (üstteki compose sorun çıkardı)
# docker run --name sql-server -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=Pass1234' -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2022-latest