version: '3'
services:
  mssql:
    container_name: mssqlvolumed
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass1234
    volumes:
    - sql-data:/var/opt/mssql

volumes:
  sql-data: