version: '3.6'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearchvolumed
    volumes:
    - elastic_data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  # logstash:
  #   image: logstash:7.16.2
  #   container_name: logstashvolumed
  #   volumes:
  #   - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf 
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #   - '9600:9600'
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m" 


  kibana:
    image: kibana:7.16.2
    container_name: kibana     
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearchvolumed:9200  
    depends_on:
      - elasticsearch 


volumes:
  elastic_data:

  # kapanıp duruyorsa docker memory size arttırmak lazım (macOS)