version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.4.14'
    restart: always
    ports:
      - '2181:2181'
  kafka1:
    image: 'bitnami/kafka:3'
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
    ports:
      - '9092:9092'

  kafka2:
    image: 'bitnami/kafka:3'
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
    ports:
      - '9093:9092'


  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka1
      - kafka2
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:9092,kafka2:9093