version: '3'
services:
  mongodb:
    container_name: mongocompose
    # MongoDB 5.0+ requires a CPU with AVX support, that is why we dont use  lates (4.4.6 )
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:




# docker run -d --rm -p 27017:27017 --name mongo1 --network mongoCluster mongo:5 mongod --replSet myReplicaSet --bind_ip localhost,mongo1
# docker run -d --rm -p 27018:27017 --name mongo2 --network mongoCluster mongo:5 mongod --replSet myReplicaSet --bind_ip localhost,mongo2 
# docker run -d --rm -p 27019:27017 --name mongo3 --network mongoCluster mongo:5 mongod --replSet myReplicaSet --bind_ip localhost,mongo3

#docker exec -it mongo1 mongosh --eval "rs.initiate({ _id: 'myReplicaSet', members: [   {_id: 0, host: 'mongo1'},   {_id: 1, host: 'mongo2'},   {_id: 2, host: 'mongo3'} ]})"

# üstteki compose çalışmıyor. alttaki komutlarla cluster oluşturabiliyoruz. en son command den sonra con string veriyor tek host ile. mongo compoass ile bağlanılıp devam edilebilir.
# replicaset oluşturduk ancak sharding için ekstra birşeyler yapmak gerekiyor muhtemelen. collection bazında yapmak gerekiyor olabilir.