version: '3'
services:
  mongodb:
    container_name: mongocompose
    # MongoDB 5.0+ requires a CPU with AVX support, that is why we dont use 
    image: mongo:4.4.6 
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: